### ISSUE TITLE
How many layers do tileserver-gl support?

### ISSUE THREAD

**Issue by haopf** [maptiler/tileserver-gl#412]
How many layers do tileserver-gl support? 
I found timeserver-gl lost some layers.

**Comment by petrsloup** [comment]
There is no hard limit on the number of styles or layers inside the styles.

But due to the structure of the project, it's better to keep the number of styles reasonable, because any additional style allocates some resources.

Even if you use a lot of style, there is no reason for the tileserver to "lose" some layers -- I can imaging a scenario where the process crashes because there's not enough memory available, but there is no mechanism for styles to be "removed" in such case.
