### ISSUE TITLE
Support newer (LTS+supported) node.js version

### ISSUE THREAD

**Issue by jfgaudreault-p** [maptiler/tileserver-gl#565]
This is a suggestion, would it be possible to support newer node.js version?
Node.js version 10 is a bit old and not supported anymore.

I tried building the docker image using newer node version but it didn't work. I haven't debugged further to try to understand why, but I read in README that node.js version 10 was required.

It would be nice if this worked with newer supported node.js version and that newer pre-build docker containers were also available.

**Comment by acalcutt** [comment]
Fixed by https://github.com/maptiler/tileserver-gl/pull/602

In the past we could not upgrade past node 10 due to mapbox-native binaries not being available. With the switch to Maplibre-Native, we can now support past node 10. Right now maplibre has binaries for Ubuntu 20.04 x64 and Macos-12 x64 (No arm right now but we are working on it), with node 10, 14, 16, 18 (10 is being removed from the next release). So this means we can get past node 10 finally.
