### ISSUE TITLE
Strange behavior with one tile

### ISSUE THREAD

**Issue by fabiuk** [maptiler/tileserver-gl#623]
Hi,

I've updated from v3.x.x. to v 4.1.1 and got to an strange behavior. I'm using tileserer as docker with planet mbtiles file.

By calling my local tileserver (http://localhost:8080/styles/english/14/9681/7633.png)  I get a error message see below. The tile should be a valid coordinate range. The strange thing is after calling the url 8x, tileserver delivers the tile.
Maybe you can help me to find out from where the issue appears. Could it be that it is my style configuration? 

```
[Error: paths outside valid range of coordinate_type]
GET /styles/english/14/9681/7633.jpeg 500 2 - 2582.974 ms
mlgl: {
  class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load tile 13/4840/3816=>13 for source openmaptiles: paths outside valid range of coordinate_type'
}
``` 
calling 8x the same url results in success:

`GET /styles/english/14/9681/7633.jpeg 200 4119 - 1720.626 ms
`

**Comment by acalcutt** [comment]
When I test with my own server and style it seems to work 
https://tiles.wifidb.net/styles/WDB_BASIC/14/9681/7633.png

Do you have an example of your style and config?

**Comment by fabiuk** [comment]
Hello thanks for the fast answer!
Attached I've added my config.json and style.json. If it works for you it means I've to find the issue in my style config isn't it? As json is not allowed to attach I changed it to txt-file.


[config.txt](https://github.com/maptiler/tileserver-gl/files/9738626/config.txt)
[english.txt](https://github.com/maptiler/tileserver-gl/files/9738627/english.txt)

**Comment by acalcutt** [comment]
I tested your style and it seemed like it worked for me. the only changes I had to make were adding spites and fonts since I didn't have them.  I would make sure you have fonts and spites correct, since the rendering will fail without them. 

This is what I used: 
[test_style.zip](https://github.com/maptiler/tileserver-gl/files/9739433/test_style.zip)

In your config, the only thing I noticed was the style paths. I thought they should be relative to the path you have set for styles. I didn't think they could be full paths, but maybe I am wrong.

What are you using for a openmaptiles planet mbtiles?

**Comment by fabiuk** [comment]
Yes spites and fonts I have available.
Will test in the next days the style with relative paths.

The planet mbtiles-file has been created with openmaptiles 3.12.1. For the next month I have the plan to create a new planet file, there I will take the latest version of openmaptiles.

**Comment by fabiuk** [comment]
I tried now some different mbtiles (no planet files) and haven't got any issue. I'm going to generate a new planet file and post the result here.

**Comment by fabiuk** [comment]
Meanwhile I generated a new planet mbtiles file with openmaptiles 3.14., the specific tiles does not provide an issue anymore.
Thanks for the fast support from your side and your engagement on the project.
