### ISSUE TITLE
Does tileServer-GL support pmtiles to render?

### ISSUE THREAD

**Issue by hayatsingh-geospoc** [maptiler/tileserver-gl#826]
It is great you want to help us making TileServer GL project better!

This is the right place only for a software bug report or a new software feature request.

NOTE: Questions about OpenMapTiles data, OpenMapTiles Server, TileHosting and other software/products do not belong here (and will not be answered)!

The usage and installation questions belongs to https://stackoverflow.com/questions/tagged/openmaptiles
A guaranteed support and consulting from the core developers via https://openmaptiles.com/support/

Please search this GitHub repo for similar requests before posting (check also closed tickets).

When reporting a problem you have with the TileServer GL software please provide:

- Clear description of the problem: What steps will lead to reproducing the error on our computer? What is exactly wrong?
- Version of the TileServer GL software you have used
- Version and name of the operating system you use or other details of your setup
- Information about your used config / styles / vector tiles
- URL / link to the specific location in a live map demo where a bug is visible is always great
- Screenshot of the problem are cool! Drag&drop an image to the report here...

We love pull requests! If you are able to code, please send us your fix or code modification via GitHub... Thanks!

**Comment by acalcutt** [comment]
Tileserver-gl does not support pmtiles at this time. However, with something like maplibre-gl-js, you could support sources from both pmtiles and tileserver, you just create a style that includes both.

**Comment by hayatsingh-geospoc** [comment]
When do we expect to see the support of PMTiles in TileServer-GL-js? @acalcutt  Please! response!

**Comment by acalcutt** [comment]
I don't expect it to be supported any time soon. I think i would be quite a feat. Currently malibre-native has no support for pmtiles and I think that would be needed for the rendering pieces of tileserver to work for static images and raster tiles.  I would support a PR if someone figured out how to get it done. 

Right now, if you aren't using the rendering features it is already possible to mix with pmtiles, since pmtiles just requires a webserver

Here is an example style that uses both pmtiles and tileserver-gl. ( https://wifidb.net/demo/pmtiles/osm-bright-gl-terrain-tileserver/style.json )
openmaptiles, TerrainSource, HillshadeSource are all small area pmtiles files hosted in the same folder as the main page. I made static tilejson files that link to them using a "pmtiles://" "tiles" source.
https://wifidb.net/demo/pmtiles/tiles_omt.json
https://wifidb.net/demo/pmtiles/tiles_terrain.json
contour_250m is a source from my tileserver-gl instance.
https://tiles.wifidb.net/data/contour_250m.json

Then I just use that that style in a Maplibre-gl-js map like
https://wifidb.net/demo/pmtiles/terrain-with-tileserver.html

I'd say the hardest part of this was generating the tilejson for the [tiles_omt.json](https://wifidb.net/demo/pmtiles/tiles_omt.json) layers . Originally I had loaded a mbtiles version of my file into tileserver-gl and just copied the tilejson from there and adapted it manually to my pmtiles source. Most examples don't use tilejson, but it was needed on the vector layers to have things like the inspect plugin work (edited)

You might also check out the tileserver [martin](https://github.com/maplibre/martin). @bdon recently added pmtiles support to martin. Just note, martin doesn't have native rendering like tileserver-gl does at this time.

**Comment by acalcutt** [comment]
I just wanted to let you know, the current version of Tileserver-GL, as of v4.6.0, now supports local and http pmtiles. It is recommended to use at least v4.6.3 though, since the have been a few bug fixes.

There is new information about how to include it in your config file at
https://maptiler-tileserver.readthedocs.io/en/latest/config.html#data

And information on how to use it in a style at
https://maptiler-tileserver.readthedocs.io/en/latest/config.html#pmtiles
