### ISSUE TITLE
raster accept XSS attack

### ISSUE THREAD

**Issue by aryansa** [maptiler/tileserver-gl#903]
The content of the key GET parameter is reflected unsanitized in an HTTP response for the application's main page, causing reflected XSS.
 
Just test the request below by commit sha `4268b73aff294a03b7acea527a5a3d1511a17247` :
http://localhost:8080/?key=rfw2r%27-alert(1)-%27y22oq#15/35.7207/51.3155

**Comment by acalcutt** [comment]
which version are you using? I thought we fixed this already. Is this a new location an issue exists?

When I try this on my instance, nothing happened

**Comment by thistehneisen** [comment]
@acalcutt I just had the same finding due to testing my clients systems integration with `tileserver-gl` and also pulled the latest version locally — I can confirm that it is fixed in the latest version (the metasymbols are escaped properly, also in `/data/v3/` endpoint).
<img width="878" alt="Screenshot 2023-07-21 at 20 32 31" src="https://github.com/maptiler/tileserver-gl/assets/6432992/8389d825-f434-4813-a9d5-2602ca4ba576">

**Comment by acalcutt** [comment]
Thanks for double checking this. I'm going to close this for now.
