### ISSUE TITLE
timeout when requesting wmts tiles 

### ISSUE THREAD

**Issue by a14stoner** [maptiler/tileserver-gl#915]
Hello everyone, 

I am using the latest tileserer-gl version 4.4.10.

I have a combination of vector-data and raster-data: 

![image](https://github.com/maptiler/tileserver-gl/assets/59861665/fffe4457-a260-4fb3-992b-1fb0e487f9e6)

When checking both layer basemap_hillshade:

![image](https://github.com/maptiler/tileserver-gl/assets/59861665/a530d166-088f-45cf-9abf-5580288dbce7)

 and basemap_hdpi

![image](https://github.com/maptiler/tileserver-gl/assets/59861665/2b6a751f-bccb-4040-9e7d-0b167047a93a)

everything works well. 
also when checking the combination of both: 

![image](https://github.com/maptiler/tileserver-gl/assets/59861665/81c48975-4a3e-46dd-bcdb-26a824e55011)

it works well. its a little bit slow but ok. 

Requesting the wmts capabilities i also get a result. But when opening the layer via QGIS i always get timeouts and no png tiles are coming back from tileserver. 

my config.json looks like this: 

```
{
  "options": {
    "paths": {
      "root": "/data",
      "fonts": "basemap_hdpi/fonts",
      "styles": ""
    },
    "log_level": "debug",
    "serveStaticMaps": true,
    "formatQuality": {
      "jpeg": 90,
      "webp": 90
    },
    "maxSize": 8192,
    "pbfAlias": "pbf"
  },
  "styles": {
    "basemap_hdpi": {
      "style": "basemap_hdpi/styles/style.json",
      "tilejson": {
        "bounds": [8.8587,46.3723,17.1608,49.0205],
        "format": "vector"
      }
    }
  },
  "data": {
    "basemap_hdpi": {
      "mbtiles": "bmapv_hdpi.mbtiles"
    },
    "basemap_hillshade": {
      "mbtiles": "bmap_ht.mbtiles"
    }
  }
}
```
I dont see anything in the logs of the container although i configured "log_level":"debug" 

```
GET /styles/basemap_hdpi/16/35163/23053.png - - - - ms
GET /styles/basemap_hdpi/16/35163/23052.png - - - - ms
GET /styles/basemap_hdpi/16/35163/23050.png - - - - ms
GET /styles/basemap_hdpi/15/17581/11526.png - - - - ms
GET /styles/basemap_hdpi/15/17579/11526.png - - - - ms
GET /styles/basemap_hdpi/15/17580/11526.png - - - - ms
GET /styles/basemap_hdpi/15/17581/11525.png - - - - ms
GET /styles/basemap_hdpi/15/17581/11524.png - - - - ms
GET /styles/basemap_hdpi/15/17578/11523.png - - - - ms
GET /styles/basemap_hdpi/15/17578/11525.png - - - - ms
GET /styles/basemap_hdpi/15/17578/11526.png - - - - ms
GET /styles/basemap_hdpi/15/17578/11524.png - - - - ms
GET /styles/basemap_hdpi/15/17581/11523.png - - - - ms
GET /styles/basemap_hdpi/15/17579/11523.png - - - - ms
GET /styles/basemap_hdpi/15/17580/11523.png - - - - ms
GET /styles/basemap_hdpi/15/17579/11527.png - - - - ms
GET /styles/basemap_hdpi/15/17581/11527.png - - - - ms
GET /styles/basemap_hdpi/15/17580/11527.png - - - - ms
GET /styles/basemap_hdpi/15/17578/11527.png - - - - ms
GET /styles/basemap_hdpi/15/17582/11526.png - - - - ms
GET /styles/basemap_hdpi/15/17582/11524.png - - - - ms
GET /styles/basemap_hdpi/15/17582/11523.png - - - - ms
GET /styles/basemap_hdpi/15/17582/11525.png - - - - ms
GET /styles/basemap_hdpi/15/17582/11527.png - - - - ms
```

any idea why this is so slow / doesnt work?

**Comment by acalcutt** [comment]
Are you able to view this in the "Raster" viewer in your style? wmts is rendered in a similar way to raster, so it is possible you are getting some error in your style with maplibre-native. Do you see any warnings at the command prompt when you look at raster view?

**Comment by a14stoner** [comment]
Ping. Maybe someone can help me :D

**Comment by acalcutt** [comment]
I notice in your requests it is looking for ".vector" files, but I think tileserver may be expecting 'pbf' there.

If you try to manually download in the browser 
`/styles/basemap_hdpi/7/64/45.vector` , which seems trange. maybe it is because you are specifying `"format": "vector"`. If you remove that does the behavior change?

typically a rendered style would be in png format, like look at this network tab when i look at a raster map
![image](https://github.com/maptiler/tileserver-gl/assets/3792408/9ce97d3c-4d70-4410-9795-a0c3fa9e524c)

**Comment by a14stoner** [comment]
you were right. removing the `"format": "vector"` in my config.json resolved the error but no tiles png files are shown: 
the requests are pending for a very long time: 

![image](https://github.com/maptiler/tileserver-gl/assets/59861665/a303b0d2-7e47-45f5-a069-1bf77d203221)

**Comment by acalcutt** [comment]
I've also seen empty tiles like that from maplibre-native when fonts or sprites are missing that are specified in your style. maplibre-native. 

What are you specifying for fonts/glyphs in your style? do you see any warnings about fonts?

**Comment by acalcutt** [comment]
Also, sometimes I find issues in my style by opening the developer console and going into the vector view. The console will sometimes log errors in your style, that will make the raster view not render.

**Comment by acalcutt** [comment]
Looking at your config, my guess is this is font related. 

In your config.json you are saying the fonts are in `basemap_hdpi/fonts` , but in your style you are also including the full path to the fonts. I think this would append the two together, so it would be looking for fonts at /data/basemap_hdpi/fonts/basemap_hdpi/fonts/{fontstack}/{range}.pbf

This fonts don't matter as much in vector view, because maplibre-gl-js web vector viewer is able to pull missing fonts from the browser. Maplibre-native needs the folts to exists because it is not able to falll back to what the browser has for fonts.

assuming your folder structure looks like
/data (mbtiles here)
/data/basemap_hdpi/sprites/sprite.json
/data/basemap_hdpi/fonts/Arial Bold/{range}.pbf
/data/basemap_hdpi/fonts/Arial Regular/{range}.pbf
/data/basemap_hdpi/styles/style.json

I would change my config like so the fonts and sprite paths are specified

config.json
```
    "paths": {
      "root": "/data",
      "fonts": "basemap_hdpi/fonts",
      "sprites": "basemap_hdpi/sprites",
      "styles": ""
    },
```

then I would change my style to remote the font and sprite paths. Also I would use the config data ids to link to my data sources without using a full url.

style.json
```
  "sprite": "sprite",
  "glyphs": "{fontstack}/{range}.pbf",
  "sources": {
    "esri": {
      "type": "vector",
      "url": "mbtiles://{basemap_hdpi}"
    },
    "basemap_hillshade": {
      "type": "raster",
      "url": "mbtiles://{basemap_hillshade}"
    }
  },
```

typically in my styles, i keep the sprites in with the style, so my config I usually don't specify a spite path and in my style I use
`"sprite": "{styleJsonFolder}/sprite",` in your case the sprites look like they are in their own folder, so I think specifying the folder in config.json then omitting the path makes sense.

In your 'basemap_hdpi/fonts' folder do the 'Arial Bold' and 'Arial Regular' font glyphs exists? I don't see that font used in styles much, so if you don't have them you could create them by dragging the windows arial font into https://maplibre.org/font-maker/

I would expect something like the attached in the end, though I don't have your mbtiles files to test it.
[basemap_hdpi.zip](https://github.com/maptiler/tileserver-gl/files/13207484/basemap_hdpi.zip)

**Comment by a14stoner** [comment]
oh my god i used your style.json and it works now...

```
ET /styles/basemap_hdpi/7/68/44.png 304 - - 0.901 ms
GET /styles/basemap_hdpi/7/68/43.png 200 11001 - 1357.422 ms
GET /styles/basemap_hdpi/7/69/43.png 200 8560 - 1357.954 ms
GET /styles/basemap_hdpi/7/69/44.png 200 131129 - 2359.188 ms
GET /styles/basemap_hdpi/7/68/45.png 200 53462 - 5092.368 ms
GET /styles/basemap_hdpi/7/67/44.png 200 49280 - 5092.946 ms
GET /styles/basemap_hdpi/7/69/45.png 200 43031 - 5093.355 ms
GET /styles/basemap_hdpi/7/70/46.png 200 355 - 2788.002 ms
GET /styles/basemap_hdpi/7/71/45.png 200 872 - 2791.615 ms
GET /styles/basemap_hdpi/7/71/46.png 200 355 - 34.272 ms
GET /styles/basemap_hdpi/7/66/42.png 200 872 - 51.770 ms
GET /styles/basemap_hdpi/7/67/46.png 200 355 - 47.366 ms
GET /styles/basemap_hdpi/7/67/45.png 200 34399 - 24.732 ms
GET /styles/basemap_hdpi/7/71/42.png 200 872 - 245.890 ms
GET /styles/basemap_hdpi/7/70/42.png 200 872 - 445.860 ms
GET /styles/basemap_hdpi/7/66/44.png 200 872 - 504.554 ms
GET /styles/basemap_hdpi/7/69/42.png 200 872 - 29.375 ms
GET /styles/basemap_hdpi/7/70/44.png 200 11157 - 465.519 ms
GET /styles/basemap_hdpi/7/71/44.png 200 872 - 801.389 ms
GET /styles/basemap_hdpi/7/69/46.png 200 355 - 781.242 ms
GET /styles/basemap_hdpi/7/66/45.png 200 872 - 1260.556 ms
GET /styles/basemap_hdpi/7/67/42.png 200 872 - 808.495 ms
GET /styles/basemap_hdpi/7/71/43.png 200 872 - 13.318 ms
GET /styles/basemap_hdpi/7/70/45.png 200 3699 - 281.541 ms
GET /styles/basemap_hdpi/7/68/42.png 200 872 - 270.398 ms
GET /styles/basemap_hdpi/7/70/43.png 200 3617 - 279.223 ms
GET /styles/basemap_hdpi/7/65/44.png 200 355 - 265.250 ms
GET /styles/basemap_hdpi/7/67/43.png 200 6145 - 284.303 ms
GET /styles/basemap_hdpi/7/66/46.png 200 355 - 20.264 ms
GET /styles/basemap_hdpi/7/68/46.png 200 355 - 268.628 ms
GET /styles/basemap_hdpi/7/66/43.png 200 872 - 280.848 ms
GET /styles/basemap_hdpi/7/65/43.png 200 355 - 258.485 ms
GET /styles/basemap_hdpi/7/72/44.png 200 355 - 266.305 ms
GET /styles/basemap_hdpi/7/72/43.png 200 355 - 24.006 ms
GET /styles/basemap_hdpi/7/65/45.png 200 355 - 14.637 ms
GET /styles/basemap_hdpi/7/65/42.png 200 355 - 16.128 ms
GET /styles/basemap_hdpi/7/72/45.png 200 355 - 23.167 ms
GET /styles/basemap_hdpi/7/72/42.png 200 355 - 27.582 ms
GET /styles/basemap_hdpi/7/65/46.png 200 355 - 22.555 ms
GET /styles/basemap_hdpi/7/72/46.png 200 355 - 19.289 ms
```
thanks a million!!!!

![image](https://github.com/maptiler/tileserver-gl/assets/59861665/36d84b97-006a-40a0-bccd-c68723f3f053)
