### ISSUE TITLE
Failed to open X display

### ISSUE THREAD

**Issue by prancius** [maptiler/tileserver-gl#978]
![image](https://github.com/maptiler/tileserver-gl/assets/13869553/678cee5b-a5a3-45f8-9667-e8a1f4c03ee7)

I have run in ubuntu 20,04 tilserver-gl + config + styles as described in doc
Server starts, but when i go to browser with first reguest server shutdown with error
Any ideas?

**Comment by acalcutt** [comment]
If you are running on a headless computer (no gui with x server) then you need to simulate X server. This is because maplibre-native depends on X server, which tileserver-gl needs to render maps.

Usually we get around this by installing xvfb, and adding this to the front of the command
`xvfb-run --server-args="-screen 0 1024x768x24" `

So for running the npm package like you are, i think you can do
`xvfb-run --server-args="-screen 0 1024x768x24" tileserver-gl`
