### ISSUE TITLE
Tileserver crashing and shutting down when given wrong encoded URI on static image

### ISSUE THREAD

**Issue by ouraios** [maptiler/tileserver-gl#981]
When a wrongly encoded character is given on the endpoint of static images generation it makes tileserver crash and shutdown instantly.

This mean that any tileserver which can generate static images can be shutted down by anyone

URL that made tileserver crash : `http://localhost:8080/styles/basic-preview/static/auto/1000x1000.png?path=enc:%4` 

Stack trace : 
```
GET /styles/basic-preview/static/auto/1000x1000.png?path=enc:%4 404 9 - 1.667 ms
GET /favicon.ico 200 5430 - 1.991 ms
file:///usr/src/app/src/serve_rendered.js:167
        PATH_PATTERN.test(decodeURIComponent(providedPath))
                          ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at extractPathsFromQuery (file:///usr/src/app/src/serve_rendered.js:167:27)
    at file:///usr/src/app/src/serve_rendered.js:1097:25
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:15
    at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/src/app/node_modules/express/lib/router/index.js:376:14)

Node.js v18.17.0
```

**Comment by acalcutt** [comment]
I can confirm this issue after testing your url. @vinayakkulkarni do you have any suggestions?

**Comment by boldtrn** [comment]
One solution I can think of would a simple try/catch. We could even think about wrapping the whole `app.get()` in a try catch to avoid crashing the server.  In the catch we return 500.

I am actually wondering right now, why this hasn't produced issues before?

**Comment by Caerbannog** [comment]
> I am actually wondering right now, why this hasn't produced issues before?

I suppose it's because the encoded polyline feature was added quite recently (January 2023) and you have to build invalid URLs to trigger the bug.

**Additionally I believe that the two `decodeURIComponent()` calls in `serve_rendered.js` should be removed.**
I can't find a valid reason for them to be there: at this point in processing, the query has already been decoded by express (through the `qs` module). The reason this was not noticed is that they don't have a measurable effect (apart from crashing).

The first call is only used in a regex test, then processing continues using `providedPath` unaffected:
https://github.com/maptiler/tileserver-gl/blob/c13e5e68218889e152d13eea1e9479a16800d3da/src/serve_rendered.js#L161-L165

The second call is used to parse options (width, color...), not pseudo-binary:
https://github.com/maptiler/tileserver-gl/blob/c13e5e68218889e152d13eea1e9479a16800d3da/src/serve_rendered.js#L439

Summary: we could remove both `decodeURIComponent()` calls.

**Comment by boldtrn** [comment]
> I suppose it's because the encoded polyline feature was added quite recently (January 2023) and you have to build invalid URLs to trigger the bug.

There are 4 methods that are async that can crash the server if an error is thrown. So my wondering was why we haven't seen any other server crashes for some other errors have been reported before.

> Summary: we could remove both decodeURIComponent() calls.

Good call, would you like to provide a PR for that?

**Comment by acalcutt** [comment]
At least with https://github.com/maptiler/tileserver-gl/pull/994 the server doesn't crash from this request anymore from this. However I wouldn't mind a new PR that tests removing decodeURIComponent() so we can see what that does.
